Feature/navigation
mendixlabs/carousel pull request #9
Opened 2016-11-29 15:04 UTC by Andries-Smit

Add navigation through images

2016-12-09 16:35 UTC, johanflint requested changes
Reviewed everything except the unit tests and the CSS change.

2016-12-09 16:35 UTC, johanflint commented on package.json
> +    "@types/big.js": "0.0.31",
Types are dev dependencies because they're only used by the typescript compiler. They aren't needed when running the code.

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/Carousel.xml
> +<widget id="com.mendix.widget.carousel.Carousel" needsEntityContext="false" xmlns="http://www.mendix.com/widget/1.0/"
I'd just keep it on one line, it's not very important information. Up to you.

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +interface CarouselState {
You can inline it as it's just one property.

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +    private getCarouselItems(images: Image[], activeIndex: number) {
This implies that the carousel items already exist and that you simply are returning them. But you are actually creating them. Why not call it `createCarouselItems` then?

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +        }
const newActiveIndex = direction === "right"
      ? activeIndex < imageCount - 1 ? activeIndex + 1 : firstIndex
      : activeIndex === firstIndex ? imageCount - 1 : activeIndex - 1;

:)

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +                onClick: () => this.moveInDirection("left")
This actually allocates memory for and creates a new closure every time `render` is called. That is not needed, just create it once in the constructor and reuse it.

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +    private getCarouselControls() {
get => create?

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/CarouselControl.ts
> +    onClick?: React.MouseEventHandler<HTMLDivElement>;
Ohhh, why use the global here?

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +        const imageCount = this.props.images.length;
Just inline it, it takes up one line to save a few chars.

2016-12-09 16:35 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> -import { DOM, createElement } from "react";
Why? The old version had logical sorting (see ASCII), now it's just odd :)

2016-12-12 06:45 UTC, edwinmp commented on package.json
> +    "@types/big.js": "0.0.31",
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/Carousel.xml
> +<widget id="com.mendix.widget.carousel.Carousel" needsEntityContext="false" xmlns="http://www.mendix.com/widget/1.0/"
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +interface CarouselState {
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +    private getCarouselItems(images: Image[], activeIndex: number) {
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +                onClick: () => this.moveInDirection("left")
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +    private getCarouselControls() {
Done.

2016-12-12 06:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +        const imageCount = this.props.images.length;
Done.

2016-12-12 06:47 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/Carousel.ts
> +        }
Done.

2016-12-12 06:47 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> -import { DOM, createElement } from "react";
Done.

2016-12-12 12:43 UTC, johanflint requested changes
Few small comments. Looking better and better! Keep up the good work.

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +            ));
The last `)` belongs to `toBeElement` and is thus on the wrong line.

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +        expect(carouselControl.hasClass("widget-carousel-control")).toBe(true);
Use the correct matcher for it, it will produce better errors if the test fails. So `expect(...).tohaveClass("...")`.

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +        expect(carouselControl.hasClass("widget-carousel-control")).toBe(true);
That also applies to other tests in this file :)

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    describe("that navigates to the", () => {
I think you forgot the word "right" here :)

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    let onClick = () => clickCount++;
If you replace this with a spy (created in the `beforeEach`), you can simply verify that it has been called later on. See my comments later :)

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    let clickCount = 0;
With a spy this can go.

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +        carouselControl = shallow(createElement(CarouselControl, { direction: "right", onClick }));
So create the spy here: `onClickSpy = jasmine.createSpy("onClick")`

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +            clickCount = 0;
Then this can go :)

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    it("responds to a single click", () => {
Then with the spy this test will be like this:

    carouselControl.simulate("click");
    
    expect(onClickSpy).toHaveBeenCalled();

2016-12-12 12:43 UTC, johanflint commented on src/com/mendix/widget/carousel/ui/Carousel.css
> +    outline: 0;
You mean "outline: none"?

2016-12-16 12:45 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    it("responds to a single click", () => {
Done.

2016-12-16 12:45 UTC, edwinmp commented on src/com/mendix/widget/carousel/ui/Carousel.css
> +    outline: 0;
Done.

2016-12-16 12:45 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +            clickCount = 0;
Done.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    describe("that navigates to the", () => {
Added.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +        expect(carouselControl.hasClass("widget-carousel-control")).toBe(true);
Done for all.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +            ));
Done.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +        carouselControl = shallow(createElement(CarouselControl, { direction: "right", onClick }));
Done.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    let onClick = () => clickCount++;
Done.

2016-12-16 12:46 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/CarouselControl.spec.ts
> +    let clickCount = 0;
Done.

2016-12-23 10:30 UTC, johanflint requested changes

2016-12-23 10:30 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> +        it("switches to the next image when the right control is clicked", () => {
I would split this test. First case: there is an image to the right and you expect that index to be active. Second case: there is no image to the right and it falls back to 0. There is specific code for that, hence the split. Same applies to navigating to the left.

2016-12-23 10:30 UTC, johanflint commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> +            // Test incomplete: not checking if carousel items are updated. Failed to successfully test
The carousel makes `CarouselItem`s for every image. It passes three props: `active`, `key` and `url`. How the `CarouselItem` renders itself is not the concern of the carousel, but that the props get passed is. So you need a separate test to verify that `active` is passed correctly and is `true` in some cases and `false` in others. So use shallow rendering for that and verify the props :).

2016-12-23 11:12 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> +        it("switches to the next image when the right control is clicked", () => {
Done.

2016-12-23 11:17 UTC, edwinmp commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> +            // Test incomplete: not checking if carousel items are updated. Failed to successfully test
That's what I had in mind too, but it failed. Following the click, the state is updated but the `CarouselItem`s are not.

```
expect(carousel.state().activeIndex).toBe(1); // successful
expect(carouselItems.at(0).props().active).toBe(false); // fails
expect(carouselItems.at(1).props().active).toBe(true); // fails
```

2016-12-23 13:00 UTC, Andries-Smit commented on src/com/mendix/widget/carousel/components/__tests__/Carousel.spec.ts
> +            // Test incomplete: not checking if carousel items are updated. Failed to successfully test
Fixed, The carouselItems are not a reference, so they should be found again after the test.

2016-12-27 10:19 UTC, johanflint approved these changes

2016-12-27 10:21 UTC, merged